# Generated by Django 2.2.11 on 2020-04-07 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='тут введите имя автора', max_length=150, verbose_name='Имя')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
                'verbose_name': 'Автор',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.Author')),
            ],
            options={
                'verbose_name_plural': 'книги',
                'verbose_name': 'книга',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Жанры',
                'verbose_name': 'Жанр',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='bookshop.Book')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
                'verbose_name': 'Комментарий',
                'db_table': 'Comment',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.Genre'),
        ),
    ]
